[2025-06-10 03:41:24,488] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:41:24,494] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:41:57,541] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:41:57,548] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:41:57,573] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:41:57,590] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:42:46,485] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:42:46,489] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:42:49,878] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:42:49,879] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:42:49,883] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:42:49,887] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:43:20,440] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:43:20,442] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:43:20,446] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:43:20,462] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:43:21,457] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:43:21,461] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:43:21,473] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:43:21,475] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:48:44,121] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:48:44,130] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:48:44,190] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 03:48:44,200] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:46:49,443] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:46:49,570] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:46:49,740] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:50:44,101] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:50:44,105] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:52:42,262] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
[2025-06-10 04:52:42,657] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
[2025-06-10 04:53:22,318] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
[2025-06-10 04:53:22,621] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
[2025-06-10 04:53:23,714] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
[2025-06-10 04:53:23,770] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
[2025-06-10 04:53:40,996] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:53:41,244] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:53:41,307] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:53:41,557] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:58:56,672] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:58:56,936] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:58:56,983] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 04:58:57,247] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:00:15,149] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:00:15,153] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:00:21,334] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:00:21,340] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:00:25,573] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:00:25,579] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:01:24,023] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:01:24,287] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:01:24,327] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:01:24,599] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:07:52,505] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:07:52,509] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:07:57,316] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:07:57,319] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:08:24,561] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:08:24,565] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:08:29,230] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:08:29,240] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:08:33,296] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:08:33,300] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:09:31,332] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:09:31,339] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:09:42,505] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:09:42,526] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:13:06,744] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:13:06,747] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:14:59,960] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:14:59,967] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:22:48,488] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:22:48,537] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:22:56,554] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 05:22:56,557] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 06:41:04,255] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 06:41:04,266] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 06:41:24,127] ERROR django.request: Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    raise TypeError
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 901, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\cloudinary\__init__.py", line 308, in url
    return self.build_url(**self.url_options)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\cloudinary\__init__.py", line 318, in build_url
    return self.__build_url(**options)[0]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\cloudinary\__init__.py", line 315, in __build_url
    return utils.cloudinary_url(public_id, **combined_options)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\cloudinary\utils.py", line 843, in cloudinary_url
    prefix = build_distribution_domain(options)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\cloudinary\utils.py", line 752, in build_distribution_domain
    raise ValueError("Must supply cloud_name in tag or in configuration")
ValueError: Must supply cloud_name in tag or in configuration
[2025-06-10 06:41:24,194] ERROR django.server: "GET / HTTP/1.1" 500 292315
[2025-06-10 06:44:23,486] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 06:44:23,496] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 06:57:16,491] ERROR django.request: Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-d13ldi24d50c739il780-a.singapore-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\views.py", line 96, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\mixins.py", line 72, in get
    response = super().get(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\views.py", line 123, in get_context_data
    site = get_current_site(self.request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\contrib\sites\shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\models\query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1620, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-d13ldi24d50c739il780-a.singapore-postgres.render.com" to address: Name or service not known

[2025-06-10 06:57:16,600] ERROR django.server: "GET /accounts/login/ HTTP/1.1" 500 275013
[2025-06-10 20:33:35,315] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:33:35,391] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:34:47,242] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:34:47,329] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:37:20,664] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:37:20,781] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:37:31,688] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:37:32,636] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:37:57,352] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:37:57,948] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:38:55,936] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:38:56,300] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:39:17,686] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:39:17,939] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:46:01,162] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:46:01,357] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:50:00,258] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:50:00,385] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:50:34,627] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:50:34,715] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:52:21,587] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:52:21,836] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\http\request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2025-06-10 20:52:45,169] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:52:45,175] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:52:55,895] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:52:55,909] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:54:49,953] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:54:49,959] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:54:56,333] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:54:56,337] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:55:01,332] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:55:01,338] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:55:07,961] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:55:08,005] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:57:01,546] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:57:01,674] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:57:01,712] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:57:01,795] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 20:57:37,341] ERROR django.request: Internal Server Error: /favicon.ico
[2025-06-10 20:57:37,342] ERROR django.server: "GET /favicon.ico HTTP/1.1" 500 145
[2025-06-10 20:57:43,982] ERROR django.request: Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'csp_nonce'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\template\base.py", line 577, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 113: 'csp_nonce'. Did you forget to register or load this tag?
[2025-06-10 20:57:44,312] ERROR django.server: "GET / HTTP/1.1" 500 145
[2025-06-10 20:57:44,400] ERROR django.request: Internal Server Error: /favicon.ico
[2025-06-10 20:57:44,411] ERROR django.server: "GET /favicon.ico HTTP/1.1" 500 145
[2025-06-10 21:02:06,000] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:02:06,014] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:02:21,710] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:02:21,716] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:04:24,220] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:04:24,225] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:04:30,318] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:04:30,322] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:05:09,277] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:05:09,283] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:08:04,417] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:08:04,422] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:08:10,941] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:08:10,945] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:54:49,573] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 21:54:49,586] ERROR django.server: You're accessing the development server over HTTPS, but it only supports HTTP.
[2025-06-10 22:12:06,233] ERROR django.request: Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\views.py", line 161, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\mixins.py", line 118, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\mixins.py", line 82, in post
    response = self.form_valid(form)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\views.py", line 172, in form_valid
    return flows.signup.complete_signup(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.request,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        by_passkey=form.by_passkey,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\internal\flows\signup.py", line 124, in complete_signup
    return perform_login(request, login)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\internal\flows\login.py", line 88, in perform_login
    return resume_login(request, login)
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\internal\flows\login.py", line 97, in resume_login
    response = ctrl.handle()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\stages.py", line 112, in handle
    response, cont = stage.handle()
                     ~~~~~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\stages.py", line 146, in handle
    send_email_confirmation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        self.request, login.user, signup=login.signup, email=login.email
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\utils.py", line 257, in send_email_confirmation
    return flows.email_verification.send_verification_email(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        request, user, signup=signup, email=email
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\internal\flows\email_verification.py", line 214, in send_verification_email
    email_address.send_confirmation(request, signup=signup)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\models.py", line 107, in send_confirmation
    confirmation.send(request, signup=signup)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\models.py", line 136, in send
    get_adapter().send_confirmation_mail(request, self, signup)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\adapter.py", line 661, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\allauth\account\adapter.py", line 211, in send_mail
    msg.send()
    ~~~~~~~~^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\mail\message.py", line 307, in send
    return self.get_connection(fail_silently).send_messages([self])
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\Users\Lanuel\Desktop\django-starter\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lanuel\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lanuel\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lanuel\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 864, in create_connection
    raise exceptions[0]
  File "C:\Users\Lanuel\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[2025-06-10 22:12:07,284] ERROR django.server: "POST /accounts/signup/ HTTP/1.1" 500 145
